N = input('Digite algo: ')
print('O tipo primitivo é',type(N))
print('É um número?',N.isnumeric())
print(' É alfabétco?',N.isalpha())
print('É tudo em maiúsculo?',N.isupper())
print('Está em minúsculas?',N.islower())
print('É somente espaços?',N.isspace())
print('É alfanumérico?',N.isalnum())
print('É um título?',N.istitle())