Nome = str(input('Digite o seu nome Completo: ')).strip()
print('Analisando seu nome....')
print(f' O seu nome completo com todas as letra maiúsculas é:\n {Nome.upper()}\n')
print(f'O seu nome completo com todas as letras minúsculas é: \n{Nome.lower()}\n')
#print(f' O seu nome tem {len(Nome.replace(' ', ''))} letras\n')
print(f'O seu nome tem: {len(Nome) - Nome.count(' ')} letras\n')
#PN = Nome.split()
#print(f'O seu primeiro nome tem {len(PN[0])} letras')
print(f' Seu primeiro nome tem {Nome.find(' ')} letras')
