tabela = ('Palmeiras', 'Flamengo', 'Athletico-PR', 'Fluminense', 'Bragantino', 'Bahia', 'Coritiba', 'São Paulo', 'Corinthians', 'Cruzeiro', 'Botafogo', 'EC Vitória', 'Atlético-MG', 'Internacional', 'Santos', 'Grêmio', 'Vasco da Gama', 'Mirassol', 'Remo', 'Chapecoense')
print('Tabela do brasileirão')
print('==' * 15)
for equipa in tabela:
	print(equipa, '\n')
print('==' * 15)
print(f'Os 5 primeiros colocados são: {tabela[:5]}')
print('==' * 15)
print(f'Os 4 últimos colocados são: {tabela[-4:]}')
print('==' * 15)
print(f'As equipas em ordem alfabética são: {sorted(tabela)}')
print('==' * 15)
